before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  -
    id: linux
    binary: rmmagent
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - linux_386
      - linux_amd64
      - linux_arm64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - windows_386
      - windows_amd64
archives:
  - format: binary
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}'
checksum:
  name_template: checksums.txt
